### ISSUE TITLE
fatal error: SNPE/SNPE.hpp: No such file or directory

### ISSUE THREAD

**Issue by dbasbabasi** [gesanqiu/SNPE_Tutorial#2]
![image](https://user-images.githubusercontent.com/13520065/194185653-b52ecd52-a622-4cb2-abb1-be2e4c7bb6e3.png)

Hi!

I am new on SNPE. I installed sdk on docker. And cloned your repo. But I encountered with this issue as in the image (fatal error: SNPE/SNPE.hpp: No such file or directory). I am sure snpe-net-run or converters work fine. I tested it. How can I manage this issue?

Thank you!
Regards!

**Comment by gesanqiu** [comment]
> ![image](https://user-images.githubusercontent.com/13520065/194185653-b52ecd52-a622-4cb2-abb1-be2e4c7bb6e3.png)
> 
> Hi!
> 
> I am new on SNPE. I installed sdk on docker. And cloned your repo. But I encountered with this issue as in the image (fatal error: SNPE/SNPE.hpp: No such file or directory). I am sure snpe-net-run or converters work fine. I tested it. How can I manage this issue?
> 
> Thank you! Regards!

Hi,

As you can see in the CMakeLists.txt, I add a include path `/usr/include/zdl`, where is the header files of SNPE located. So you should copy the whole header directory(`${SNPE_ROOT}/include/zdl`) of SNPE into your docker contianer manually, which is in the SNPE SDK zip file.

Thanks,
Ricardo Lu.

**Comment by dbasbabasi** [comment]
Hi Ricardo,

Thank you so much I solved this issue but it gives another error. How can I solve it? Also I sent an email to you. If you can check it, I will be really glad. 

![image](https://user-images.githubusercontent.com/13520065/194369826-24772cca-f917-4cc9-b5eb-3363ba43e62b.png)

Thank you,
Regards,
Dervis

**Comment by gesanqiu** [comment]
> Hi Ricardo,
> 
> Thank you so much I solved this issue but it gives another error. How can I solve it? Also I sent an email to you. If you can check it, I will be really glad.
> 
> ![image](https://user-images.githubusercontent.com/13520065/194369826-24772cca-f917-4cc9-b5eb-3363ba43e62b.png)
> 
> Thank you, Regards, Dervis

Hi Derivis,

So in your email, I known your hardware platform, the SNPE SDK is not in its base line image, so you need to push them into your device manually, like the include headers I mentioned before. 
The libraries locate in `${SNPE_ROOT}/lib`, choose the right platform(if your OS is LU, it should be **aarch64-ubuntu-gcc-7.5**). And if your SNPE SDK is too new, maybe you can't find them, you need downloads the lower version from the Qualcomm pages.
As for running on DSP/AIP runtime dependencies, please check the email, because I'm not sure whether these info are open for Qualcomm, sorry.

Thanks,
Ricardo Lu

**Comment by gesanqiu** [comment]
Please feel free and reopen this issue if you still have prbllem.

**Comment by dbasbabasi** [comment]
@gesanqiu Can you contact with me?
